
name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      # Browserstack fix https://github.com/browserstack/browserstack-runner/issues/224#issuecomment-803409764
      - run: rm ./package-lock.json
      - run: npm i
      - run: npm test
      - run: npm run test:browserstack
        env:
            BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}

  release:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
